spring:
  application:
    name: rmq-backend-worker
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    connection-timeout: 5000
    template:
      exchange-response: exchange.response
      error-routing-key: error.rout.key
      success-routing-key: success.rout.key
      request-queue: request

  zipkin:
    base-url: http://localhost:9411
    sender.type: web

  output:
    ansi:
      enabled: ALWAYS

  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    propagation:
      type: B3
    baggage:
      remote-fields: trace-id
    tags:
      application: payment-worker  # Nome único para o serviço
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
    logging:
      pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

rmq:
  tracing:
    service-name: rmq-consumer-worker

server:
  port: 8082

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %m%n"